### PR TITLE
Removed unused variables from DDJ200.headmix

### PR DESCRIPTION
**Pull request by fkbreitl**
This is a fix for `CodeFactor — 2 issues found.`
You need to pull it otherwise it will not go into the Mixxx repository.

### CODE REVIEW

**Comment by dan-giddins** [comment]
@fkbreitl I'm just wondering, should we be doing work on the MIXXX fork instead of this repository (as in you fork my fork of MIXXX, and add the controller work there)? It would mean that I wouldn't have to manually keep copying the files across (me merging a PR from your fork into my fork, should mean it automatically updates my PR into MIXXX), but it would make it harder for people to find the DDJ 200 scripts if they want to get the controller working for themselves now....
What do you think?

**Comment by dan-giddins** [comment]
@fkbreitl Never mind, I just realised that you would have to build MIXXX each time you wanted to test a change, so I think they way we are doing it now is the best

**Comment by fkbreitl** [comment]
Yes, I already thought about this problem. I plan to fork the DDJ200 mapping as soon as it gets merged, so I can develop independent and don't need to ask you to pull my PRs. Since the mapping is just javascript, I don't need to build anything.

I already started to extend the mapping to 4 decks. Lets see when I will find the time to complete it and when our PR gets finally merged. To me the Mixxx procedure seem overly complicated and time consuming...

**Comment by dan-giddins** [comment]
I guess you could change the controller scripts location to point to the
folder in the repo. If you want to try that, fork my fork of MIXXX and see
if you can get it working (the updated scripts are in my fork)

**Comment by fkbreitl** [comment]
Sounds complicated. I would rather fix what is missing to get it in the Mixxx repo.
I still don't understand what is holding it back.
I guess we have to wait for Holzhaus' response.

**Pull request merged**
