### PR TITLE
Add leds sync between mixxx interface and controller

### PR DESCRIPTION
**Pull request by geovannimp**
Those changes keep leds synced if changes are made directly in mixxx interface.

### CODE REVIEW

**Comment by dan-giddins** [comment]
@geovannimp support for the ddj-200 is now included in MIXXX by default. I would recommend forking MIXXX and applying your changes to the ddj-200 script.js that is part of the mixxx repo, as my version of the code is out of date (and there is no need to keep it up to date)

Do you think I should delete this repo?

**Comment by geovannimp** [comment]
Actually my changes are made over mixxx 2.3 version, so this code are not so out of date. 

I will submit those fixes to mixxx repo too.

**Comment by geovannimp** [comment]
About deleting the repo:

I made changes to transition fx button, replacing the auto dj mode (that I believe nobody uses) with a toggle mode.

- Turned off (default) = Pads in hotcue mode
- Blinking = Pads in Loop mode
- Turned on = Pads in effect mode

With this changes we have same functions as other programs. But as I replaced transition FX button I think its not appropriate to ship this as default at mixxx.

Are you available to keep this repo as a alternative version with some extras or have any suggestion?

**Comment by dan-giddins** [comment]
@geovannimp I think I am going to delete this, as I only hosted this to vend a mapping for ddj-200 whilst it was not apart of MIXXX by default.


https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility
> Deleting a public repository
When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other 
repositories are forked off of this new parent and subsequent pull requests go to this new parent.

Look like if I delete this repo, another public repo becomes the parent, probably yours...

I don't really want to keep this open, as I think the current version of MIXXX with the built in mapping is better than what I have.
You are of course more than welcome to keep your fork open and vend your version of this mapping!

If you are happy, please close this PR and I will go ahead and delete this repo.

**Comment by geovannimp** [comment]
Thanks, I will close

**Pull request closed without merging**
